### ISSUE TITLE
Pending reviews' radio button text is unreadable

### ISSUE THREAD

**Issue by AlFasGD** [acoop133/GithubDarkTheme#85] opened 2019-09-11 15:49 UTC
The radio button text on the pending review in the conversation tab is unreadable. 
![pending review test png](https://user-images.githubusercontent.com/8298332/64712984-cd075880-d4c4-11e9-8f9b-18e9e59dd9f9.png)

**Comment by acoop133** [comment] 2019-09-11 18:07
I see, 
though my test PR bug mismatches your bug. strange. 

Can you check if you're on the latest update? 
if you are on the latest and all of the text are still not visible, what browser are you using?

you can update from here > https://userstyles.org/styles/168350/githubdarktheme
if your button says "Style Installed" then you have the latest version.


![image](https://user-images.githubusercontent.com/19627023/64721863-39825780-d4c5-11e9-9f72-e1ca336d075c.png)


ps. hello fellow osu player ;)

**Comment by acoop133** [comment] 2019-09-16 22:46
I believe i have fixed the title color.
As i cant reproduce your bug, its hard for me to fix it.

I will close this ticket for now.

perhaps you can make a nonsense PR on this repo and ill start a review to see if i can reproduce it, as the screenshot above is for my own PR, it might be different if its on others.

**Closed by acoop133** 2019-09-16 22:46 UTC
Labels: Accepted
